from src.infra.datasources.design_wall_datasource import DesignWallDataSource
from src.infra.datasources.user_profile_datasource import UserProfileDataSource
from src.infra.datasources.talent_market_datasource import TalentMarketDataSource